trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: PowerShellScriptJob
  displayName: 'PowerShell Script Job'
  steps:
  - task: PowerShell@2
    displayName: 'Run PowerShell Script'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Hello, Azure Pipelines!"
        # Add your PowerShell script here
       
        # This is a sample shell script
        echo "Hello from the shell script!"
        echo "This script is running as part of the build process."
        echo "You can add any commands or logic here that you need for your build"